---
Parameters:

  AvailabilityZone:
    Type: String
    Default: us-west-2a
  AmazonLinux2AMI:
    Type: String
    Default: ami-0ceecbb0f30a902a6

Resources:
  DockerComposeInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref AmazonLinux2AMI
      InstanceType: t2.micro
      UserData: 
        Fn::Base64:
          | 
          #!/bin/bash
          yum update -y

          # Install Docker
          amazon-linux-extras install docker -y
          service docker start
          systemctl enable docker
          usermod -a -G docker ec2-user
          chmod 666 /var/run/docker.sock               

          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
          sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
          sudo chmod +x /usr/bin/docker-compose
          
         

          # Install git in your EC2 instance
          yum install git -y

          # Clone and run a sample application
          cd ~
          git clone https://github.com/manishgsp/kpmg.git
          cd kpmg
          docker-compose --file docker-compose.yml up

      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTTPSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp

  HTTPSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable standard web access
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 3000
          ToPort: 3000
          IpProtocol: tcp
